/**
 * Type declarations for the @mitre/jsonix runtime.
 *
 * The data shapes below (TypedNamedValue, XML.QName, XML.Calendar, XML.Duration and the
 * TYPE_NAME discriminant) are a contract with the declaration files that
 * jsonix-schema-compiler emits with -generateTypeScript: generated files carry their own
 * structurally identical copies, so anything the runtime returns can be typed with a
 * generated element type, and anything typed with a generated type can be marshalled.
 * tests/typescript guards that contract. Change them together or not at all.
 */

export namespace Jsonix {
  export namespace XML {
    /**
     * A qualified name (Jsonix.XML.QName). Runtime instances always carry every field;
     * marshal input may give only namespaceURI and localPart.
     */
    export interface QName {
      namespaceURI: string;
      localPart: string;
      prefix?: string;
      /** "{namespaceURI}localPart" */
      key?: string;
      /** "prefix:localPart" */
      string?: string;
    }

    /**
     * The representation of xs:date, xs:time, xs:dateTime and the xs:g* types
     * (Jsonix.XML.Calendar). Unset fields are NaN. Jsonix never returns a JavaScript Date.
     */
    export interface Calendar {
      year?: number;
      month?: number;
      day?: number;
      hour?: number;
      minute?: number;
      second?: number;
      fractionalSecond?: number;
      timezone?: number;
    }

    /** The representation of xs:duration values. sign is 1 or -1. */
    export interface Duration {
      sign?: number;
      years?: number;
      months?: number;
      days?: number;
      hours?: number;
      minutes?: number;
      seconds?: number;
    }
  }

  /**
   * An element: what an unmarshaller returns, what a marshaller accepts, and the value of an
   * elementRef property. Generated declarations alias this per global element, for example
   * `type PurchaseOrderElement = TypedNamedValue<PurchaseOrderType>`.
   */
  export interface TypedNamedValue<T = unknown> {
    name: XML.QName;
    value: T;
  }

  /**
   * A mapping module as consumed by `new Jsonix.Context([...])`: a plain object generated by
   * jsonix-schema-compiler or written by hand. Generated declarations type theirs as
   * `JsonixMapping<RootElement>`, whose phantom `__rootElement` carries the union of the module's
   * global element types; `Context` reads it to infer what its unmarshallers return.
   */
  export interface Mapping<R = unknown> {
    readonly __rootElement?: R;
    readonly [key: string]: unknown;
  }

  /**
   * The union of the root element types of the given mapping(s), or the untyped element when a
   * mapping does not declare one (hand-written mappings, generated ones compiled without
   * -generateTypeScript).
   */
  export type RootElementOf<M> = M extends { readonly __rootElement?: infer R }
    ? NonNullable<R> extends TypedNamedValue
      ? NonNullable<R>
      : TypedNamedValue
    : TypedNamedValue;

  export interface ContextOptions {
    /** Maps namespace URIs to the prefixes used when marshalling. */
    namespacePrefixes?: { [namespaceURI: string]: string };
    /** Whether xsi:type attributes are honoured when unmarshalling and written when marshalling. Defaults to true. */
    supportXsiType?: boolean;
    /** The mapping style, by name or as a custom style object. Defaults to 'standard'. */
    mappingStyle?: 'standard' | 'simplified' | object;
  }

  /**
   * Options for unmarshalURL (passed to the XMLHttpRequest transport) and unmarshalFile
   * (passed to fs.readFile).
   */
  export type UnmarshalOptions = object;

  /**
   * R is the union of root element types inferred from the context's mappings; each method can
   * narrow it with an explicit type argument, e.g. `unmarshalString<PurchaseOrderElement>(xml)`.
   */
  export interface Unmarshaller<R extends TypedNamedValue = TypedNamedValue> {
    /** Parses an XML string. */
    unmarshalString<E extends TypedNamedValue = R>(text: string): E;
    /** Unmarshals a DOM document (or element). */
    unmarshalDocument<E extends TypedNamedValue = R>(doc: Node, scope?: unknown): E;
    /** Loads the URL with XMLHttpRequest and unmarshals the response. */
    unmarshalURL<E extends TypedNamedValue = R>(
      url: string,
      callback: (unmarshalled: E) => void,
      options?: UnmarshalOptions
    ): void;
    /** Node.js only: reads the file and unmarshals it. Throws in environments without a file system. */
    unmarshalFile<E extends TypedNamedValue = R>(
      fileName: string,
      callback: (unmarshalled: E) => void,
      options?: UnmarshalOptions
    ): void;
  }

  export interface Marshaller {
    /** Serialises an element to an XML string. */
    marshalString<E extends TypedNamedValue>(element: E): string;
    /** Serialises an element to a DOM document. */
    marshalDocument<E extends TypedNamedValue>(element: E): Document;
  }

  /**
   * M is inferred from the mappings passed to the constructor; `createUnmarshaller()` then returns
   * elements typed as the union of those mappings' root elements. The constraint is `object`, not
   * `Mapping`, so hand-written mappings typed with an interface (no index signature) are accepted.
   */
  export class Context<M extends object = Mapping> {
    /**
     * @param mappings Mapping modules (generated or hand-written). Cross-module references are
     *   resolved by name, in any order.
     * @param options Optional configuration.
     */
    constructor(mappings: M[], options?: ContextOptions);

    createUnmarshaller(): Unmarshaller<RootElementOf<M>>;
    createMarshaller(): Marshaller;

    getTypeInfoByName(name: string): TypeInfo;
    getTypeInfoByTypeName(typeName: string): TypeInfo;
    getTypeInfoByTypeNameKey(typeNameKey: string): TypeInfo;
    getElementInfo(name: string, scope: string): any;
    getSubstitutionMembers(name: string): any;
    getNamespaceURI(prefix: string): any;
    getPrefix(namespaceURI: string, defaultPrefix: string): any;

    builtinTypeInfos: {
      Jsonix: {
        Schema: {
          XSD: {
            AnyType: { INSTANCE: {} };
            AnySimpleType: { INSTANCE: {} };
            AnyURI: { INSTANCE: {} };
            Base64Binary: { INSTANCE: {} };
            Boolean: { INSTANCE: {} };
            Byte: { INSTANCE: {} };
            Calendar: { INSTANCE: {} };
            DateAsDate: { INSTANCE: {} };
            Date: { INSTANCE: {} };
            DateTimeAsDate: { INSTANCE: {} };
            DateTime: { INSTANCE: {} };
            Decimal: { INSTANCE: {} };
            Double: { INSTANCE: {} };
            Duration: { INSTANCE: {} };
            Float: { INSTANCE: {} };
            GDay: { INSTANCE: {} };
            GMonth: { INSTANCE: {} };
            GMonthDay: { INSTANCE: {} };
            GYear: { INSTANCE: {} };
            GYearMonth: { INSTANCE: {} };
            HexBinary: { INSTANCE: {} };
            ID: { INSTANCE: {} };
            IDREF: { INSTANCE: {} };
            IDREFS: { INSTANCE: {} };
            Int: { INSTANCE: {} };
            Integer: { INSTANCE: {} };
            Language: { INSTANCE: {} };
            Long: { INSTANCE: {} };
            Name: { INSTANCE: {} };
            NCName: { INSTANCE: {} };
            NegativeInteger: { INSTANCE: {} };
            NMToken: { INSTANCE: {} };
            NMTokens: { INSTANCE: {} };
            NonNegativeInteger: { INSTANCE: {} };
            NonPositiveInteger: { INSTANCE: {} };
            NormalizedString: { INSTANCE: {} };
            Number: { INSTANCE: {} };
            PositiveInteger: { INSTANCE: {} };
            QName: { INSTANCE: {} };
            Short: { INSTANCE: {} };
            String: { INSTANCE: {} };
            Strings: { INSTANCE: {} };
            TimeAsDate: { INSTANCE: {} };
            Time: { INSTANCE: {} };
            Token: { INSTANCE: {} };
            UnsignedByte: { INSTANCE: {} };
            UnsignedInt: { INSTANCE: {} };
            UnsignedLong: { INSTANCE: {} };
            UnsignedShort: { INSTANCE: {} };
          };
        };
      };
    }[];

    // private
    elementInfos: ClassInfo[];
  }

  // Mapping internals (as built by Context). These describe the mapping model, not the data.

  export interface Styled {
    CLASS_NAME: string;
    mappingStyle: Object;
  }

  export interface TypeInfo {
    name: string;
    baseTypeInfo: TypeInfo;
  }

  export interface EnumLeafInfo extends TypeInfo {
    name: string;
    baseTypeInfo: TypeInfo;
    entries: { [name: string]: string };
    keys: { [index: number]: string };
    values: { [index: number]: string };
    built: boolean;
  }

  export interface PropertyInfo {
    CLASS_NAME: string;
    name: string;
    collection: boolean;
    targetNamespace: string;
    defaultElementNamespaceURI: string;
    defaultAttributeNamespaceURI: string;
    built: boolean;
  }

  export interface AbstractElementPropertyInfo extends PropertyInfo {
    wrapperElement: XML.QName;
    allowDom: boolean;
    allowTypedObject: boolean;
    mixed: boolean;
  }

  export interface ElementPropertyInfo extends AbstractElementPropertyInfo {
    typeInfo: TypeInfo | string;
    elementName: XML.QName;
  }

  export interface ClassInfo extends TypeInfo, Styled {
    CLASS_NAME: string;
    localName: string;
    typeName: XML.QName;
    instanceFactory: {};
    properties: { [index: number]: PropertyInfo };
    propertiesMap: { [name: string]: PropertyInfo };
    structure: {
      elements: { [fqn: string]: PropertyInfo };
      attributes: {};
      anyAttribute: {};
      value: {};
      any: {};
    };
    targetNamespace: string;
    defaultElementNamespaceURI: string;
    defaultAttributeNamespaceURI: string;
    built: boolean;
    propertyInfoCreators: {
      aa: { aa: any };
      anyAttribute: { aa: any };
      ae: { ae: any };
      anyElement: { ae: any };
      a: { a: any };
      attribute: { a: any };
      em: { em: any };
      elementMap: { em: any };
      e: { e: any };
      element: { e: any };
      es: { es: any };
      elements: { es: any };
      er: { er: any };
      elementRef: { er: any };
      ers: { ers: any };
      elementRefs: { ers: any };
      v: { v: any };
      value: { v: any };
    };
  }
}

/**
 * Backwards compatibility: versions up to 3.0.11 declared these as global (ambient) interfaces.
 * Prefer the Jsonix.* names.
 * @deprecated
 */
declare global {
  /** @deprecated use Jsonix.Unmarshaller */
  interface Unmarshaller extends Jsonix.Unmarshaller {}
  /** @deprecated use Jsonix.Marshaller */
  interface Marshaller extends Jsonix.Marshaller {}
  /** @deprecated use Jsonix.XML.QName */
  interface QName extends Jsonix.XML.QName {
    CLASS_NAME: string;
  }
  /** @deprecated use Jsonix.Styled */
  interface Styled extends Jsonix.Styled {}
  /** @deprecated use Jsonix.TypeInfo */
  interface TypeInfo extends Jsonix.TypeInfo {}
  /** @deprecated use Jsonix.EnumLeafInfo */
  interface EnumLeafInfo extends Jsonix.EnumLeafInfo {}
  /** @deprecated use Jsonix.PropertyInfo */
  interface PropertyInfo extends Jsonix.PropertyInfo {}
  /** @deprecated use Jsonix.AbstractElementPropertyInfo */
  interface AbstractElementPropertyInfo extends Jsonix.AbstractElementPropertyInfo {}
  /** @deprecated use Jsonix.ElementPropertyInfo */
  interface ElementPropertyInfo extends Jsonix.ElementPropertyInfo {}
  /** @deprecated use Jsonix.ClassInfo */
  interface ClassInfo extends Jsonix.ClassInfo {}
}
